name: deploy static website to AWS-S3

on:
  push:
    branches:
      - main
  
env:
  AWS_REGION: us-east-1
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - name: List files before upload
        run: |
          ls -l ./ 
          
      - name: Deploy to AWS S3
        run: |
          aws s3 cp ./index.html s3://pruebabucket-s3-cicd/index.html
          aws s3 cp ./prueba.pdf s3://pruebabucket-s3-cicd/prueba.html
